### ISSUE TITLE
Whether tauri-2.0.0-alpha can be supported

### ISSUE THREAD

**Issue by mrzhjyw** [ahkohd/tauri-nspanel#15]

**Comment by ahkohd** [comment]
@mrzhjyw I'll wait until version 2.0.0 is officially released.

**Comment by ahkohd** [comment]
> > I'll wait until version 2.0.0 is officially released.
> 
> Perhaps a [message](https://discord.com/channels/616186924390023171/731495028677148753/1206206255107014716) from Simon will incentivize you to do v2 support)
> 
> <img alt="image" width="911" src="https://private-user-images.githubusercontent.com/30116541/303960056-f14c8d6b-90fe-4b09-827e-e779c8f7e0c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjU1MDIsIm5iZiI6MTcwODcyNTIwMiwicGF0aCI6Ii8zMDExNjU0MS8zMDM5NjAwNTYtZjE0YzhkNmItOTBmZS00YjA5LTgyN2UtZTc3OWM4ZjdlMGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIxNTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MTg5NWY4YWNlNjY3ZWNiM2U3ZGE0OTIxYzM0YTY5YzRkZTYxZWNkYzE4ZGJjZjkwZDQ1MzY5ZjZlMTRmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E9C5-tjg8mMN9wvNwpr470SsfJYgw07hcnFUOQ4HMPk">

Haha, okay, I'll start the upgrade.

**Comment by yetone** [comment]
‌‌‌‌‌@ahkohd 

Tauri 2.0-beta has also been released, really looking forward to supporting it.

**Comment by ahkohd** [comment]
Sure, this weekend, I will write and release support for version 2.

**Comment by yetone** [comment]
‌‌‌‌@ahkohd That's fantastic, really looking forward to it!

**Comment by yetone** [comment]
> > ‌‌‌‌@ahkohd That's fantastic, really looking forward to it!
> 
> What errors are you getting that require this plugin to be adapted to v.2?

I haven't tried using this plugin because I looked at Cargo.toml and it still depends on tauri 1.0.

**Comment by ahkohd** [comment]
Hello gents,

It's ready, please help test it out and give me feedbacks.

https://github.com/ahkohd/tauri-nspanel/tree/v2

**Comment by yetone** [comment]
‌‌‌That's so cool! I'll find some time to test it out!

**Comment by ahkohd** [comment]
Okay then, I'll close this issue and mark it as done. If you face any problems, please don't hesitate to create a new issue.
