### ISSUE TITLE
Unable to Set Window Style to NSWindowStyleMaskNonactivatingPanel

### ISSUE THREAD

**Issue by zzzze** [ahkohd/tauri-nspanel#19]
Your implementation comes very close to perfection. 
However, to achieve an effect similar to the Spotlight popup, it's necessary to set the window style to NSWindowStyleMaskNonactivatingPanel. This conclusion is based on the response to a related [issue](https://stackoverflow.com/questions/46023769/how-to-show-a-window-without-stealing-focus-on-macos), and I have also developed a native app myself, which indeed confirmed this necessity. 
<img width="884" alt="image" src="https://github.com/ahkohd/tauri-nspanel/assets/32935001/0b73bfd0-cf09-474a-9985-48e78c46cd17">
<img width="857" alt="image" src="https://github.com/ahkohd/tauri-nspanel/assets/32935001/c2b46b45-dbf9-4a14-a405-71da3d98bee3">
Ultimately, I discovered that [cocoa](https://github.com/ryanmcgrath/cacao/blob/trunk/src/appkit/window/enums.rs#L7) does not actually provide an enumeration value for NSWindowStyleMaskNonactivatingPanel. After setting it to an enumeration value I created, the program crashed. Do you know why this might be happening?

**Comment by ahkohd** [comment]
Hello @zzzze `tauri-nspanel` is a generic library to create panel from window for a various purpose i.e to build menubar app panel, spotlight window e.t.c. this repo does not include a spotlight implementation.

However, I get your message. If you set a panel style mask to a `NonActivatingPanel` it should work. 
I know because it's used in a production app, https://usezap.sh. 

Below is the excerpt of the setup for Zap.

```rust
#[allow(non_upper_case_globals)]
const NSWindowStyleMaskNonActivatingPanel: i32 = 1 << 7;

fn swizzle_to_panel(window: &tauri::Window<Wry>) {
  let panel_delegate = panel_delegate!(SpotlightPanelDelegate {
    window_did_become_key,
    window_did_resign_key,
    window_did_update
  });

  let handle = window.app_handle();
  panel_delegate.set_listener(Box::new(move |delegate_name: String| {
    match delegate_name.as_str() {
      "window_did_become_key" => {
        handle.trigger_global("window_did_become_key", None);
      }
      "window_did_resign_key" => {
        handle.trigger_global("window_did_resign_key", None);
      }
      "window_did_update" => {
        handle.trigger_global("window_did_update", None);
      }
      _ => (),
    }
  }));

  let panel = window
    .app_handle()
    .get_window("main")
    .unwrap()
    .to_panel()
    .unwrap();
  panel.set_level(NSMainMenuWindowLevel + 1);
  panel.set_collection_behaviour(
    NSWindowCollectionBehavior::NSWindowCollectionBehaviorCanJoinAllSpaces
      | NSWindowCollectionBehavior::NSWindowCollectionBehaviorStationary
      | NSWindowCollectionBehavior::NSWindowCollectionBehaviorFullScreenAuxiliary,
  );
  panel.set_style_mask(NSWindowStyleMaskNonActivatingPanel);
  panel.set_delegate(panel_delegate);
}
```

**Comment by ahkohd** [comment]
You can refer here, https://github.com/ahkohd/tauri-macos-spotlight-example/blob/08afa57235b3693bd9bc7af9ef17a075ce0c5432/src-tauri/src/spotlight.rs#L465

**Comment by zzzze** [comment]
Thank you @ahkohd, I'll go check out the code of that project.

**Comment by ahkohd** [comment]
@zzzze, You don't want to convert a window that is initialized with decorations set to `true`, i.e `NSTitledWindowMask` to an `NSWindowStyleMaskNonActivatingPanel` panel. Make sure you set the window's decoration to `false`, before swizzling it to `NSPanel`.

**Comment by ahkohd** [comment]
I've got a new macOS Menubar app example using the `tauri-nspanel` library, and this one's super useful!  It demonstrates how to use NSWindowStyleMaskNonActivatingPanel for those times you need a menubar element that doesn't steal focus.

Get the code here: https://github.com/ahkohd/tauri-macos-menubar-app-example

**Comment by zzzze** [comment]
You're right, indeed there's no issue. Amazing, the implementation now is perfect.
