### ISSUE TITLE
How to convert to NSpanel after tauri::WindowBuilder::new

### ISSUE THREAD

**Issue by doroved** [ahkohd/tauri-nspanel#22]
Can you tell me how to convert a window to NSpanel in this function after creating it?
```rs
#[tauri::command]
async fn create_window(app: tauri::AppHandle) {
  let window = tauri::WindowBuilder::new(&app, "label", tauri::WindowUrl::External("https://tauri.app/".parse().unwrap()))
    .build()
    .unwrap();
    
    let panel = window.to_panel().unwrap();
    panel.set_style_mask(NSWindowStyleMaskNonActivatingPanel);
    panel.show();
}
```
I have tried different ways, nothing works. Most often I get this error
```
Thread 'tokio-runtime-worker' panicked at /Users/doroved/.cargo/git/checkouts/tauri-nspanel-47b5b83dc190123c/04e9eb3/src/raw_nspanel.rs:134:30:
Uncaught exception <NSException: 0x12e940540>
```

**Comment by ahkohd** [comment]
Please follow the example, my guess it that you forget to set your panel delegates.

https://github.com/ahkohd/tauri-nspanel/blob/04e9eb3c7ddec969073e8c74d7624f2ae83d05a9/examples/vanilla/src-tauri/src/main.rs#L26

**Comment by ahkohd** [comment]
Have you tried running the example from this repo?

**Comment by ahkohd** [comment]
If you do not mind can you share a repo where we can collaborate, identify and fix the issue.

**Comment by ahkohd** [comment]
<img width="1597" alt="image" src="https://github.com/ahkohd/tauri-nspanel/assets/13041443/462e4b97-8719-4ec0-ae25-0fdb668a7ad4">

it worked on my end!

<img width="862" alt="image" src="https://github.com/ahkohd/tauri-nspanel/assets/13041443/85669a85-179f-4127-9e06-5eea34fba8b6">


<img width="679" alt="image" src="https://github.com/ahkohd/tauri-nspanel/assets/13041443/e80b8b3e-d084-44a8-9887-3f42cc565911">



One thing I noticed, you are creating the panel in an async method, that won't work. All window functions are meant to be run on the main thread.

**Comment by ahkohd** [comment]
Whenever you want to do an objc/macOS window-related operation, run it on the main thread.

In this, sample code, all I just did was remove the async keyword.

```rust
#[tauri::command]
fn create_window(app: tauri::AppHandle) {
  let window = tauri::WindowBuilder::new(&app, "label", tauri::WindowUrl::External("https://tauri.app/".parse().unwrap()))
    .build()
    .unwrap();
    
    let panel = window.to_panel().unwrap();
    panel.set_style_mask(NSWindowStyleMaskNonActivatingPanel);
    panel.show();
}
```

**Comment by ahkohd** [comment]
can you share a screenshot of your code?

**Comment by ahkohd** [comment]
Ahh, one last thing, a panel cannot have a window decoration-style mask. This means you have to turn off the decoration before you convert the window to a panel.

<img width="1066" alt="image" src="https://github.com/ahkohd/tauri-nspanel/assets/13041443/2ddbeaa4-6a87-4af5-a522-dadf98c2f864">

**Comment by ahkohd** [comment]
You can use this to set the corner radius of your panel:

```rust
pub fn add_corner_radius(ns_window: id, radius: f64) {
  unsafe {
    let ns_view: id = ns_window.contentView();
    let _: () = msg_send![ns_view, wantsLayer];

    let ns_layer: id = msg_send![ns_view, layer];
    let _: () = msg_send![ns_layer, setCornerRadius: radius];
  }
}
```

**Comment by ahkohd** [comment]
> > Ahh, one last thing, avoid initializing a window you want to convert to a (non-activating, `NSNonactivatingPanelMask`) panel with decorations set to `true`, `NSTitledWindowMask`. It will lead to unexpected behavior and crash.
> 
> It would be cool if you could specify it in the documentation + an example of launching a window and converting to NSpanel in async main, which we've figured out here. Maybe it will help someone in the future.

I'll create new examples for `NonActivatingPanel` and create a panel in an `async` function.

**Comment by ahkohd** [comment]
"I just had a problem, when I opened a new window from NSpanel, when I changed focus from NSpanel to the new window, this new window would abruptly change its position. It's not always possible to catch this behavior.
So I decided that I would convert the new window to NSpanel, but this is where the other problems I described at the beginning of the post occurred)"

I don't fully understand this part.

Anyway to keep things concise, as the question you raised is already solved, you may want to close this issue.

**Comment by ahkohd** [comment]
Okay,

```rust
use objc::base::id;

let win_hndl: id = window.ns_window() as _;

add_corner_radius(win_hndl, 23.0);
```

**Comment by ahkohd** [comment]
You can ask more questions on Discord, or create a new issue if any.

**Comment by ahkohd** [comment]
@doroved I have created an example Menubar macOS app using the https://github.com/ahkohd/tauri-nspanel.
Please have a look at it: https://github.com/ahkohd/tauri-macos-menubar-app-example.
