### ISSUE TITLE
NSPanel closes when interacting with native context menu

### ISSUE THREAD

**Issue by doroved** [ahkohd/tauri-nspanel#27]
Hi.
When we open the context menu and click on or off a menu item, NSPanel closes.
Is there any way to fix this? Thanks)

**UPD:**
After the NSPanel closes, we see the focus go away from the Arc browser and if you call the context menu in the NSPanel after that, it will not close.

https://github.com/ahkohd/tauri-nspanel/assets/30116541/3ca6b124-fc87-43ad-9c7e-6aa81d5c116e

**Comment by ahkohd** [comment]
Hello @doroved,

Thank you for raising this issue, although it falls outside the scope of `tauri-panel`. Could you please close this issue here and open a new one in the https://github.com/ahkohd/tauri-nspanel repository, where it would be more suitable?
