### ISSUE TITLE
How to focus panel when shown?

### ISSUE THREAD

**Issue by ijsnow** [ahkohd/tauri-nspanel#30]
How can I make sure the panel is in focus when I show it?

My window config in `tauri.conf.json` contains `"focus": true` but I guess that doesn't work once I hide/show the window again. I have code roughly identical to the example app for init/show/hiding the panel. In my UI I have an input that I'd like to be focused when the panel is shown. I have some code that makes sure that happens, but it only happens once I click the panel. 

I've tried manually calling the `make_key_window` and `make_key_and_order_front` functions as well as just `show` and none seem to work.

Thanks!

**Comment by ahkohd** [comment]
Hey @ijsnow sorry for the late response.

You can call tauri's `Window.set_focus()`

```rust
let panel = app_handle.get_webview_panel("main").unwrap();

// ***

panel.show().unwrap();

// ***

let window = app_handle.get_webview_window("main").unwrap();

window.set_focus().unwrap();
```

**Comment by ijsnow** [comment]
That worked! I think I actually had an error in my client code that caused the apps event loop to stop
