### ISSUE TITLE
The example app doesn't seem to run

### ISSUE THREAD

**Issue by HuakunShen** [ahkohd/tauri-nspanel#35]

**Comment by ahkohd** [comment]
See the following example projects that use tauri-nspanel:
- https://github.com/ahkohd/tauri-macos-spotlight-example/tree/v2
- https://github.com/ahkohd/tauri-macos-menubar-app-example

**Comment by ahkohd** [comment]
See the commit at https://github.com/ahkohd/tauri-nspanel/commit/ff5ba21e1eaa0c5c21b87e8789efe419c9587473, as it fixes the broken example in this repository.
