### ISSUE TITLE
Calling `panel.show()` leads to a crash.

### ISSUE THREAD

**Issue by ayangweb** [ahkohd/tauri-nspanel#37]
Hey 👋, I'm trying to implement in macos that windows don't grab the focus of other windows, but I'm having some problems! The app crashes when I call `panel.show()`!

Inspired by your comment: https://github.com/tauri-apps/tauri/issues/5566#issuecomment-2409184685

Crash Demo:

https://github.com/user-attachments/assets/5473f1bb-1399-474b-94f1-3405189c3be7

The desired effect:

https://github.com/user-attachments/assets/c3182dfe-35f8-48ba-a17a-a2008af1cd49

**Comment by ahkohd** [comment]
By the way:
Your screen recording shows that your panel window has a native title bar. Please remove it, as users can use the native title bar to activate the app or zoom the window, which may lead to a crash because you set the window's non-activating flag.

_FYI: After converting a window to a panel, avoid calling `window.maximize()` as it will crash the panel. You cannot maximize a panel._

**Comment by ahkohd** [comment]
Can you share your crash log? This will help me identify the issue. Please run it with `RUST_BACKTRACE=1`.

Also, I can help you more if you can create a public repo with minimal reproduction.

**Comment by ayangweb** [comment]
I forgot to post the config item by the way, the one I set to panel is the main window with the title bar already removed!

```json
{
  "windows": [
    {
      "label": "main",
      "title": "EcoPaste",
      "url": "index.html/#/",
      "width": 360,
      "height": 600,
      "minWidth": 360,
      "minHeight": 600,
      "maximizable": false,
      "decorations": false,
      "visible": false,
      "transparent": true,
      "alwaysOnTop": true,
      "acceptFirstMouse": true,
      "skipTaskbar": true
    },
    {
      "label": "preference",
      "url": "index.html/#/preference/clipboard",
      "width": 700,
      "height": 480,
      "minWidth": 700,
      "minHeight": 480,
      "center": true,
      "visible": false,
      "transparent": true,
      "maximizable": false,
      "hiddenTitle": true,
      "skipTaskbar": true,
      "titleBarStyle": "Overlay",
      "windowEffects": {
        "effects": ["sidebar"],
        "state": "active"
      }
    }
  ],
}
```


https://github.com/user-attachments/assets/8c830c7e-c73c-4950-a2df-88d2766e02ef

I'll try to write a minimal reproducible case!

**Comment by ahkohd** [comment]
> I forgot to post the config item by the way, the one I set to panel is the main window with the title bar already removed!
> 
> ```json
> {
>   "windows": [
>     {
>       "label": "main",
>       "title": "EcoPaste",
>       "url": "index.html/#/",
>       "width": 360,
>       "height": 600,
>       "minWidth": 360,
>       "minHeight": 600,
>       "maximizable": false,
>       "decorations": false,
>       "visible": false,
>       "transparent": true,
>       "alwaysOnTop": true,
>       "acceptFirstMouse": true,
>       "skipTaskbar": true
>     },
>     {
>       "label": "preference",
>       "url": "index.html/#/preference/clipboard",
>       "width": 700,
>       "height": 480,
>       "minWidth": 700,
>       "minHeight": 480,
>       "center": true,
>       "visible": false,
>       "transparent": true,
>       "maximizable": false,
>       "hiddenTitle": true,
>       "skipTaskbar": true,
>       "titleBarStyle": "Overlay",
>       "windowEffects": {
>         "effects": ["sidebar"],
>         "state": "active"
>       }
>     }
>   ],
> }
> ```
> 
>  iShot_2024-10-15_08.37.06.mp4 
> I'll try to write a minimal reproducible case!

Okay nice, waiting for the repo.

**Comment by ayangweb** [comment]
I just tried again and it doesn't crash! Sorry for the interruption 🌹

**Comment by ayangweb** [comment]
Hey 👋, excuse me, do you know how nspanel supports changing window size?

**Comment by ahkohd** [comment]
> Hey 👋, excuse me, do you know how nspanel supports changing window size?

Do you mean resizable nspanel? https://github.com/ahkohd/tauri-macos-menubar-app-example/issues/31

**Comment by ayangweb** [comment]
Thanks, it's great that the minimum size tauri configuration is also in effect!

**Comment by ayangweb** [comment]
The reason my app is crashing is because I'm using `panel.show` in the plugin in customization, but I don't know how to fix it!

**Comment by ayangweb** [comment]
https://github.com/ayangweb/tauri-nspanel-demo

Do `panel.show` and `window.show` have the same effect?

https://github.com/user-attachments/assets/089e2531-097d-4c6a-86ea-992b9d9ae686

**Comment by ahkohd** [comment]
I have checked your demo repo: https://github.com/ayangweb/tauri-nspanel-demo.

1. When you convert a window to a panel, always use the panel methods instead of the window methods.
2. Use `panel.show` to display a panel. To hide a panel, call the `order_out` method, i.e., `panel.order_out()`.
3. Always ensure that any windowing function runs on the main thread. This is why your app was crashing; you were calling `panel.show` in an `async` tauri command.

If your command must be async, ensure that the part calling the windowing functions, such as `show` or `order_out`, runs on the main thread.

A refactored [command.rs](https://github.com/ayangweb/tauri-nspanel-demo/blob/1ad4103e26a8bc5844be86bc1cb7a2677cb5c3d8/src-tauri/plugins/window/src/commands.rs#L1):
```rust
#[command]
pub fn hide_show<R: Runtime>(app_handle: AppHandle<R>) {
    let panel = app_handle
        .get_webview_panel("main")
        .expect("unable to get window");

    panel.show();
}

#[command]
pub fn hide_window<R: Runtime>(app_handle: AppHandle<R>) {
    let panel = app_handle
        .get_webview_panel("main")
        .expect("unable to get window");

    if panel.is_visible() {
        panel.order_out(None);
    }
}

/// An example async tauri command.
/// We ensure that panel.{is_visible, order_out} is ran on the main thread

#[command]
pub async fn async_hide_window<R: Runtime>(app_handle: AppHandle<R>) {
   // do your async tasks

    // run the panel function on the main thread
    let handle = app_handle.clone();
    app_handle
        .run_on_main_thread(move || {
            let panel = handle
                .get_webview_panel("main")
                .expect("unable to get window");

            if panel.is_visible() {
                panel.order_out(None);
            }
        })
        .unwrap();
}
```

You can check the repo's demo: https://github.com/ahkohd/tauri-nspanel/blob/v2/examples/vanilla/src-tauri/src/main.rs

**Comment by ahkohd** [comment]
I plan to more guide for this plugin, covering additional use cases and offering more usage examples.

**Comment by ayangweb** [comment]
Thank you. It does work.

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/967a2856-4599-4684-a550-b21cbd4ee0f5

Hey, thank you very much for such a great plugin, I see that your rust is very well written, I wonder if there is a chance to learn from you and accomplish this function of auto-pasting after the window of [EcoPaste](https://github.com/EcoPasteHub/EcoPaste) has been converted to `ns_panel`!

Code for the paste plugin：
https://github.com/ayangweb/ayangweb-EcoPaste/blob/macos_ns_panel/src-tauri/src/plugins/paste/src/commands/mac.rs

It works fine without switching to `ns_panel`, but not after switching to `ns_panel`! I don't know what to do about this problem!

**Comment by ahkohd** [comment]
You want to detect when the panel becomes and resigns as the key window:

```rust
            let main_window = app.get_webview_window("main").unwrap();

            let panel = main_window.to_panel().unwrap();

            panel.set_level(NSMainMenuWindowLevel + 1);

            let delegate = panel_delegate!(EcoPanelDelegate {
                window_did_become_key,
                window_did_resign_key
            });

            let handle = app.handle().clone();

            delegate.set_listener(Box::new(move |delegate_name: String| {
                match delegate_name.as_str() {
                    "window_did_become_key" => {
                        // emit a global event when the panel becomes the key window
                        handle.emit("eco_panel_did_become_key", ()).unwrap();
                    }
                    "window_did_resign_key" => 
                     // emit a global event when the panel resigns as the key window
                        handle.emit("eco_panel_did_resign_key", ()).unwrap();
                    }
                    _ => (),
                }
            }));

            panel.set_delegate(delegate);
```

You can listen to the events in other part of your Rust application:
```rust
            app_handle.listen("eco_panel_did_become_key", |_| {
                // do something
            });

            app_handle.listen("eco_panel_did_resign_key", |_| {
                // do something
            });

```
In your frontend code:
```js
    listen("eco_panel_did_become_key", () => {
      // do something
    });

    listen("eco_panel_did_resign_key", () => {
      // do something
    });
```
For here you can write the code that pastes when the panel resigns as the key window.

**Comment by ayangweb** [comment]
Thanks, this does listen for `ns_panel` to focus and blur 🥳, but `focus_previous_window` still doesn't trigger `window_did_resign_key`, I'm not a great rust learner, sorry for the intrusion!

https://github.com/ayangweb/ayangweb-EcoPaste/blob/8f2d9def4a5043026342f926d950900b5d2b5546/src-tauri/src/plugins/paste/src/commands/mac.rs#L82

https://github.com/user-attachments/assets/cbbb1d0a-3412-41b8-aab7-a865a1de68c1

**Comment by ayangweb** [comment]
Another problem is that my window is fixable, and I'm trying to complete the [paste](https://github.com/ayangweb/ayangweb-EcoPaste/blob/8f2d9def4a5043026342f926d950900b5d2b5546/src-tauri/src/plugins/paste/src/commands/mac.rs#L99) function in, but it seems complicated.😄

https://github.com/user-attachments/assets/67a9746f-f38b-478c-ae9c-005b48687c15

**Comment by ahkohd** [comment]
> Thanks, this does listen for `ns_panel` to focus and blur 🥳, but `focus_previous_window` still doesn't trigger `window_did_resign_key`, I'm not a great rust learner, sorry for the intrusion!
> 
> https://github.com/ayangweb/ayangweb-EcoPaste/blob/8f2d9def4a5043026342f926d950900b5d2b5546/src-tauri/src/plugins/paste/src/commands/mac.rs#L82
> 
>  iShot_2024-10-23_17.29.52.mp4

When you use `panel.show()` and `panel.order_out()` it doesn't steal focus from the active window! It only becomes they key window and first responder.

What this means is that you don't have to call the `focus_previous_window`  function as that window still has the focus.

```rust
pub async fn paste() {
    let script =
        r#"osascript -e 'tell application "System Events" to keystroke "v" using command down'"#;

    std::process::Command::new("sh")
        .arg("-c")
        .arg(script)
        .output()
        .expect("failed to execute process");
}
```

**Comment by ayangweb** [comment]
I tested it, and it still doesn't work, maybe I have to actively trigger `window_did_resign_key` when pasting, but I don't know how to implement the active trigger?

**Comment by ayangweb** [comment]
Wow, great, I realized the effect this way! Thank you very much for the solution idea!

```rs
pub async fn paste<R: Runtime>(app_handle: AppHandle<R>) {
    let handle = app_handle.clone();

    let _ = app_handle.run_on_main_thread(move || {
        let panel = handle.get_webview_panel(MAIN_WINDOW_LABEL).unwrap();

        panel.resign_key_window();
    });

    // focus_previous_window();

    let script =
        r#"osascript -e 'tell application "System Events" to keystroke "v" using command down'"#;

    std::process::Command::new("sh")
        .arg("-c")
        .arg(script)
        .output()
        .expect("failed to execute process");
}
```

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/1eef7354-eca7-4bdb-96a4-162da7a94fb2

**Comment by ayangweb** [comment]
Thanks for the plugin and the ideas you provided for implementation, really helped me a lot!🌹

**Comment by ahkohd** [comment]
> Thanks for the plugin and the ideas you provided for implementation, really helped me a lot!🌹

Are all problems now resolved?

You're welcome! You can always reach out to me anytime, I am more than happy to help.

**Comment by ayangweb** [comment]
> > Thanks for the plugin and the ideas you provided for implementation, really helped me a lot!🌹
> 
> Are all problems now resolved?
> 
> You're welcome! You can always reach out to me anytime, I am more than happy to help.

Thank you, there are no other problems at the moment, if I encounter some more complicated and difficult to solve problems, I will ask you, thank you very much🌹

**Comment by ayangweb** [comment]
Sorry to bother you so soon! Hahaha 🤣 I suddenly realized a problem, my own [`window-state`](https://github.com/EcoPasteHub/EcoPaste/blob/master/src-tauri/src/plugins/window-state/src/commands.rs) plugin I wrote is not working for the main window in macos, I see that panel provides the `set_content_size` method, but not the method to get the window size and position related!

```rs
let delegate = panel_delegate!(EcoPanelDelegate {
    window_did_resize,
    window_did_move
});

delegate.set_listener(Box::new(move |delegate_name: String| {
    match delegate_name.as_str() {
        "window_did_resize" => {
            println!("window_did_resize");
        }
        "window_did_move" => {
            println!("window_did_move");
        }
        _ => (),
    }
}));
```

The above code triggers `window_did_resize` and `window_did_move`, but as per chatgpt's answer of ` let frame = panel.frame()` to get the size and position of the window, but the panel has no `frame` method.


https://github.com/user-attachments/assets/2438750a-b499-4cd2-b3cf-a37585191c14

**Comment by ahkohd** [comment]
> Sorry to bother you so soon! Hahaha 🤣 I suddenly realized a problem, my own [`window-state`](https://github.com/EcoPasteHub/EcoPaste/blob/master/src-tauri/src/plugins/window-state/src/commands.rs) plugin I wrote is not working for the main window in macos, I see that panel provides the `set_content_size` method, but not the method to get the window size and position related!
> 
> ```rust
> let delegate = panel_delegate!(EcoPanelDelegate {
>     window_did_resize,
>     window_did_move
> });
> 
> delegate.set_listener(Box::new(move |delegate_name: String| {
>     match delegate_name.as_str() {
>         "window_did_resize" => {
>             println!("window_did_resize");
>         }
>         "window_did_move" => {
>             println!("window_did_move");
>         }
>         _ => (),
>     }
> }));
> ```
> 
> The above code triggers `window_did_resize` and `window_did_move`, but as per chatgpt's answer of ` let frame = panel.frame()` to get the size and position of the window, but the panel has no `frame` method.
> 
>  iShot_2024-10-23_21.04.12.mp4

You can use the tauri window.position and size api. it should work.
```rust
 let window = handle.get_webview_window(MAIN_WINDOW_LABEL).unwrap();

// call window. {inner_size, position, e.t.c}
```

**Comment by ayangweb** [comment]
It works for `ns_window`, but not for `ns_panel`!

https://github.com/user-attachments/assets/c27cff66-a42b-49ba-b43e-b87f6bb85bfa

**Comment by ayangweb** [comment]
`ns_window`

https://github.com/user-attachments/assets/0afece32-a088-41b8-aca3-8b702ba3bed0

**Comment by ahkohd** [comment]
How do you detect when to save the state? That is where the issue is. It's not detecting that the panel has been resized or moved since the standard tauri window resized and moved event won't work with the panel anymore

**Comment by ayangweb** [comment]
`ns_panel` Double-clicking on a blank space just crashes it. Hahaha, I'm really sorry to bother you with so many questions!😁

https://github.com/user-attachments/assets/1d6f7d40-1867-4619-86a2-6ff04db00e97

**Comment by ayangweb** [comment]
> How do you detect when save the state? That is where the issue is. It's not detecting that the panel has been resized or moved since the standard tauri window resized and moved event won't work with the panel anymore

Haha, yeah oh, I'll optimize it! I got confused writing code!🤣

<img width="1541" alt="image" src="https://github.com/user-attachments/assets/92017958-a500-42c0-b9fb-a995e5059d36">

**Comment by ahkohd** [comment]
The fix should be straight forward.
```rust
 let delegate = panel_delegate!(EcoPanelDelegate {
                window_did_become_key,
                window_did_resign_key,
                window_did_resize,
                window_did_move
            });

            let handle = app.handle().clone();

            delegate.set_listener(Box::new(move |delegate_name: String| {
                match delegate_name.as_str() {
                    "window_did_become_key" => {
                        // emit a global event when the panel becomes the key window
                        handle.emit("eco_panel_did_become_key", ()).unwrap();
                    }
                    "window_did_resign_key" => 
                     // emit a global event when the panel resigns as the key window
                        handle.emit("eco_panel_did_resign_key", ()).unwrap();
                    }
                    "window_did_resize" => {
                        handle.emit("eco_panel_did_resize", ()).unwrap();
                    }
                    "window_did_move" => {
                        handle.emit("eco_panel_did_move", ()).unwrap();
                    }
                    _ => (),
                }
            }));
```

then 
```rust
            app_handle.listen("eco_panel_did_move", |_| {
                // do something like saving state
            });

            app_handle.listen("eco_panel_did_resize", |_| {
                // do something like saving state
            });

```

**Comment by ahkohd** [comment]
> `ns_panel` Double-clicking on a blank space just crashes it. Hahaha, I'm really sorry to bother you with so many questions!😁
> 
>  iShot_2024-10-23_21.23.13.mp4

Yes this is expected, you cannot call` window.maximize()` on a panel, it will crash.

**Comment by ayangweb** [comment]
> The fix should be straight forward.
> 
> ```rust
>  let delegate = panel_delegate!(EcoPanelDelegate {
>                 window_did_become_key,
>                 window_did_resign_key,
>                 window_did_resize,
>                 window_did_move
>             });
> 
>             let handle = app.handle().clone();
> 
>             delegate.set_listener(Box::new(move |delegate_name: String| {
>                 match delegate_name.as_str() {
>                     "window_did_become_key" => {
>                         // emit a global event when the panel becomes the key window
>                         handle.emit("eco_panel_did_become_key", ()).unwrap();
>                     }
>                     "window_did_resign_key" => 
>                      // emit a global event when the panel resigns as the key window
>                         handle.emit("eco_panel_did_resign_key", ()).unwrap();
>                     }
>                     "window_did_resize" => {
>                         handle.emit("eco_panel_did_resize", ()).unwrap();
>                     }
>                     "window_did_move" => {
>                         handle.emit("eco_panel_did_move", ()).unwrap();
>                     }
>                     _ => (),
>                 }
>             }));
> ```
> 
> then
> 
> ```rust
>             app_handle.listen("eco_panel_did_move", |_| {
>                 // do something like saving state
>             });
> 
>             app_handle.listen("eco_panel_did_resize", |_| {
>                 // do something like saving state
>             });
> ```

Ok, thanks, I know how to solve this problem🥰

**Comment by ayangweb** [comment]
> > `ns_panel` Double-clicking on a blank space just crashes it. Hahaha, I'm really sorry to bother you with so many questions!😁
> > iShot_2024-10-23_21.23.13.mp4
> 
> Yes this is expected, you cannot call` window.maximize()` on a panel, it will crash.

<img width="1541" alt="image" src="https://github.com/user-attachments/assets/d1683735-1d02-4a6b-b0d9-9cc1cba0fa70">

`maximizable` is always false, I also didn't write `window.maximize()` in the code, which seems to be tauri's default behavior?

**Comment by ahkohd** [comment]
> -

Yes, this doesn't prevent calling maximise on the panel

**Comment by ahkohd** [comment]
are you using tauri-drag-region?

**Comment by ayangweb** [comment]
> are you using tauri-drag-region?

Yes, I used it.

**Comment by ahkohd** [comment]
> > are you using tauri-drag-region?
> 
> Yes, I used it.

on the panel yea?

**Comment by ayangweb** [comment]
> > > are you using tauri-drag-region?
> > 
> > 
> > Yes, I used it.
> 
> on the panel yea?

yea

**Comment by ahkohd** [comment]
> > > > are you using tauri-drag-region?
> > > 
> > > 
> > > Yes, I used it.
> > 
> > 
> > on the panel yea?
> 
> yea

okay cool, comment that part out first and try and double to see if it crashes. I can tell it won't.

**Comment by ayangweb** [comment]
Since it was on `ns_window`, I converted to `ns_panel` and did not remove it!

**Comment by ayangweb** [comment]
> > > > > are you using tauri-drag-region?
> > > > 
> > > > 
> > > > Yes, I used it.
> > > 
> > > 
> > > on the panel yea?
> > 
> > 
> > yea
> 
> okay cool, comment that part out first and try and double to see if it crashes

Okay, I'll try!

**Comment by ayangweb** [comment]
I tried it and double-clicking does stop crashing, but the window won't do any dragging either!

**Comment by ahkohd** [comment]
yes, I know that is not the fix, it was just to explain the issue to you.

**Comment by ahkohd** [comment]
in your panel permissions file, deny maximise.
```json
{
  "permissions": [
    "core:default",
    "core:window:deny-maximize"
  ]
}
```
this ensures when some script calls maximize on your panel in the JS land, it fails as it's not permitted.

**Comment by ayangweb** [comment]
> in your panel permissions file, deny maximise.
> 
> ```json
> {
>   "permissions": [
>     "core:default",
>     "core:window:deny-maximize"
>   ]
> }
> ```
> 
> which this when some script calls maximize on your panel in the JS land, it fails as it's not permitted

https://github.com/user-attachments/assets/09c4ba37-2237-40ee-95da-6a2d7bfc4127

Disabling `maximize` will also crash!

**Comment by ahkohd** [comment]
> > in your panel permissions file, deny maximise.
> > ```json
> > {
> >   "permissions": [
> >     "core:default",
> >     "core:window:deny-maximize"
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which this when some script calls maximize on your panel in the JS land, it fails as it's not permitted
> 
>  iShot_2024-10-23_21.48.17.mp4 
> Disabling `maximize` will also crash!

make it specific for the main window! i see you're using ["*"]

**Comment by ahkohd** [comment]
```json
{
  "identifier": "panel-capability",
  "windows": [
    "main"
  ],
  "webviews": [
    "main"
  ],
  "platforms": [
    "macOS",
  ],
  "permissions": [
    "core:default",
    "core:window:deny-maximize"
  ]
}
```

**Comment by ayangweb** [comment]
> ```json
>  "core:window:deny-maximize"
> ```

It's the same crash!

<img width="519" alt="image" src="https://github.com/user-attachments/assets/0937c29b-256c-4e44-9f28-7e1124ff3a91">

**Comment by ahkohd** [comment]
> > ```json
> >  "core:window:deny-maximize"
> > ```
> 
> It's the same crash!
> 
> <img alt="image" width="519" src="https://private-user-images.githubusercontent.com/75017711/379302371-0937c29b-256c-4e44-9f28-7e1124ff3a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTIxMzcsIm5iZiI6MTcyOTY5MTgzNywicGF0aCI6Ii83NTAxNzcxMS8zNzkzMDIzNzEtMDkzN2MyOWItMjU2Yy00ZTQ0LTlmMjgtN2UxMTI0ZmYzYTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEzNTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMGMzOGFiZjllOTk5OTdhNDAyZTk1NWRkODliNWM2NzAxZDEzOTMyMmIzNjExMTAwMjY3ZjBiOTJiZDIwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l4_9hie6UmrupXGUloGltaDy6LQjKx_vAtiIAUy7MxQ">

can you remove core:default

**Comment by ayangweb** [comment]
`core:window:deny-internal-toggle-maximize` Just deny this permission!

**Comment by ayangweb** [comment]
I found this permission in the console after removing the `core:default` permission!🤣

Thanks for the thoughts.

https://github.com/user-attachments/assets/26431c61-b936-4116-8a3b-2f37744a64ab

**Comment by ahkohd** [comment]
> I found this permission in the console after removing the `core:default` permission!🤣
> 
>  iShot_2024-10-23_22.02.46.mp4

Yea, cool. I knew somehow maximize is been called and core:default is likely preluding some permissions that allows this.

**Comment by ayangweb** [comment]
> > I found this permission in the console after removing the `core:default` permission!🤣
> > iShot_2024-10-23_22.02.46.mp4
> 
> Yea, cool. I knew somehow maximize is been called and core:default is likely preluding some perssion that allows this.

Haha, great, I'll use this method to troubleshoot such issues in the future, thanks!

**Comment by ayangweb** [comment]
Hey👋, sorry for having another question for you!

`panel.set_level(NSMainMenuWindowLevel + 1)` will cause the system's Simplified Chinese input method to be overwritten 🤣

https://github.com/user-attachments/assets/7987f9ac-4186-4ef3-8372-c1bf910319d1

**Comment by ahkohd** [comment]
> Hey👋, sorry for having another question for you!
> 
> `panel.set_level(NSMainMenuWindowLevel + 1)` will cause the system's Simplified Chinese input method to be overwritten 🤣
> 
>  iShot_2024-10-23_23.47.20.mp4

You can play with the levels, hard code it to 4, see if it solves your problem,

**Comment by ayangweb** [comment]
`panel.set_level(4)` does work, but then the window is under the docking station.

**Comment by ayangweb** [comment]
I don't know how it's possible with swift native apps, that's cool!

https://github.com/user-attachments/assets/d22cbcd2-9190-4528-8031-c0170dc36d7e

**Comment by ahkohd** [comment]
can you try 5?

**Comment by ayangweb** [comment]
I fixed this at https://github.com/EcoPasteHub/EcoPaste/pull/733/files, 20 up will override the system input method, but then the window can't be above the top menu bar anymore, to get the window above the top menu bar it has to be `NSMainMenuWindowLevel + 1`, hahaha, this problem is so strange! I'll be looking into that one!

https://github.com/user-attachments/assets/73df018f-3a55-4000-aa8c-4f02334fd25d

**Comment by ahkohd** [comment]
based!

**Comment by ayangweb** [comment]
Hey👋, and sorry to bother you again, do you know if you can achieve something like macos-panel on Windows?🌹

**Comment by ahkohd** [comment]
I don't know, I haven't done windows programming in any capacity. But it should be possible. However `tauri-nspanel` is macOS exclusive.

**Comment by ayangweb** [comment]
> I don't know, I haven't done windows programming in any capacity. But it should be possible. However `tauri-nspanel` is macOS exclusive.

Ok, thanks, I'll look into it again!🌹
