### ISSUE TITLE
Native traffic lights on MacOS?

### ISSUE THREAD

**Issue by joakim** [ahkohd/tauri-nspanel#38]
I'd like to create NSPanel windows like MacOS' Character Viewer or Help, with small traffic lights in the upper left corner. The titlebar/toolbar can be custom, but the traffic lights must be native because they're so complex.

Is it possible to add support for small native traffic lights in this plugin? If not, do you know of any alternative ways to achieve that in an NSPanel window?

![Screenshot 2024-10-19 at 10 56 41](https://github.com/user-attachments/assets/e957ae88-1c33-41f0-8bd9-6aaf8b2f3209)

**Comment by ahkohd** [comment]
Hello, sorry for the super late response. To achieve this use the utility window style mask: https://developer.apple.com/documentation/appkit/nswindow/stylemask-swift.struct/utilitywindow?language=objc

```rust
#[allow(non_upper_case_globals)]
pub const NSWindowStyleMaskUtilityWindow: i32 = 1 << 4;

panel.set_style_mask(NSWindowStyleMaskUtilityWindow);
```

**Comment by joakim** [comment]
Thank you, @ahkohd! No worries, it's open source, you're sharing this great plugin for free 🙂
