### ISSUE TITLE
error: failed to select a version for `tauri`

### ISSUE THREAD

**Issue by RainyNight9** [ahkohd/tauri-nspanel#40]
error: failed to select a version for `tauri`.
    ... required by package `tauri-nspanel v2.0.0 (https://github.com/ahkohd/tauri-nspanel?branch=v2#e38d989c)`
    ... which satisfies git dependency `tauri-nspanel` of package `coco v0.1.0 (/Users/rain/Desktop/zhangbin/infini/coco-app/src-tauri)`
versions that meet the requirements `^2.0.6` are: 2.0.6

the package `tauri` links to the native library `Tauri`, but it conflicts with a previous package which links to `Tauri` as well:
package `tauri v2.0.5`

**Comment by ahkohd** [comment]
update your project's tauri version to `v2.0.6` or point to an older revision of this package:

```toml
tauri-nspanel = { git = "https://github.com/ahkohd/tauri-nspanel", rev = "005240c" }
```
