### ISSUE TITLE
Webview is still running after being closed

### ISSUE THREAD

**Issue by egoist** [ahkohd/tauri-nspanel#42]
If you try to call `close_panel` in the example:

https://github.com/ahkohd/tauri-nspanel/blob/e38d989c5e97c5a55d90277765e2508b4f296832/examples/vanilla/src-tauri/src/main.rs#L70

The webview process is there after closing the NSPanel:

![CleanShot 2024-11-21 at 20 37 09@2x](https://github.com/user-attachments/assets/31c84f7e-2433-45f7-9a81-1e04a1bd5de8)

Is there a way to fully close the NSPanel?

**Comment by ahkohd** [comment]
https://github.com/ahkohd/tauri-nspanel/blob/e38d989c5e97c5a55d90277765e2508b4f296832/examples/vanilla/src-tauri/src/main.rs#L69

1. `panel.close()` will destroy(close) the panel when  `panel.release_when_closed(true)`.

**Comment by ahkohd** [comment]
2. I'm unsure if the behavior you observed is an issue with Tauri or MacOS. To understand what I mean, try creating a regular window alongside your main window and then close the window; if I'm correct, you should observe the same behavior.

**Comment by ahkohd** [comment]
I closed this for two reasons: inactivity and the fact that it is not a `tauri-nspanel` issue, as mentioned above.
