### ISSUE TITLE
“panel” Invoke “set_level” app exit

### ISSUE THREAD

**Issue by liu2356414337** [ahkohd/tauri-nspanel#43]
<img width="962" alt="iShot_2024-11-30_16 22 46" src="https://github.com/user-attachments/assets/915b4d1a-35b1-4c20-8496-eb5697c27852">

> Why does the program run to "67" line,Program exit

**Comment by ahkohd** [comment]
I'm not sure what you mean. Perhaps you could check out this example: https://github.com/ahkohd/tauri-nspanel/blob/e38d989c5e97c5a55d90277765e2508b4f296832/examples/vanilla/src-tauri/src/main.rs#L26

**Comment by ahkohd** [comment]
Closed due to inactivity.

Feel free to reopen if you have further questions.
